### ISSUE TITLE
Logo / Splash screen

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#1]
Logo, Icon and Splash screen need to be updated.

Pending to receive work from graphic designer.

**Comment by aguycalled** [comment]
New icon set:

[AppIcons-3.zip](https://github.com/aguycalled/WhisperWallet/files/8466898/AppIcons-3.zip)

Sketch for the splash and main screens (not definitive yet, but let's put it already):

[ImageSets-2.zip](https://github.com/aguycalled/WhisperWallet/files/8466903/ImageSets-2.zip)

How main screen would look like:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/24814046/162809268-5f004631-56bf-4993-89dd-f58df156d267.png">

Changes needed in the main screen:

- Change image size to 250x250px
- Change buttons color to #a98bbd

**Comment by aguycalled** [comment]
New icon set:

[AppIcons-3.zip](https://github.com/aguycalled/WhisperWallet/files/8466898/AppIcons-3.zip)

Sketch for the splash and main screens (not definitive yet, but let's put it already):

[ImageSets-2.zip](https://github.com/aguycalled/WhisperWallet/files/8466903/ImageSets-2.zip)

How main screen would look like:

<img width="334" alt="image" src="https://user-images.githubusercontent.com/24814046/162809268-5f004631-56bf-4993-89dd-f58df156d267.png">

Changes needed in the main screen:

- Change image size to 250x250px
- Change buttons color to #a98bbd

**Comment by tsejerome** [comment]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/20391660/164152389-5db06c17-73f8-48a6-a1b9-eb13921fcf4f.png">
^ This will be used as native screen logo in the drawer

<img width="404" alt="image" src="https://user-images.githubusercontent.com/20391660/164152451-8ed82ad7-3b17-4f3b-a91e-bc17717cb305.png">
^ This will be used as the image in the boot splash and in Intro.tsx
