### ISSUE TITLE
Lock screen when switching app

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/WhisperWallet#109]
Currently, when the lock for switching apps are enabled, the lock comes up when switching back to the wallet which is good. However, user can actually click cancel and quickly interact with the wallet before the lock is prompting again. The greatly reduces the purpose of that lock. The wallet should probably be in a locked stage or remove the ability to click cancel. Note that there is a window for interaction with the wallet when switching back to the wallet app as well.

**Comment by aguycalled** [comment]
fixed in `manual-pin`
