### ISSUE TITLE
Crash when cancel wallet creation

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/WhisperWallet#113]
App will crash when trying to create a new wallet then hit the back button on the upper left.

**Comment by aguycalled** [comment]
could you show a video? the back button should not be available but covered by the blurry background

**Comment by chasingkirkjufell** [comment]
https://user-images.githubusercontent.com/38635377/165884227-69f0e4a1-c32a-48e9-be9c-82bdf6986d1d.MOV

**Comment by aguycalled** [comment]
I think it is fixed now, please reopen if it persists
