### ISSUE TITLE
Change Biometrics Configuration UI from Settings Page

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#121]
- Rename from 'Biometrics Configuration' to 'Auto-lock wallet'
- Instead of showing a popup dialog with the question, do it with an embedded toggle like this: 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/24814046/166151066-cb93cd9e-859d-46b2-bf37-413360702617.png">

**Comment by tsejerome** [comment]
I'm thinking if this overlaps with the locking type, so we shd combine both option tgt

**Comment by aguycalled** [comment]
the best way to combine it would be to have a specific page for both settings instead of a modal (I think)

**Comment by tsejerome** [comment]
oh then I thot of another simpler way
just hide the Biometric Configuration part when we set security as none, but we still assume ppl won't set security as none by default (when they first use the app)
