### ISSUE TITLE
Send Tokens screen does not auto select From field when sending to someone

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#123]
On the “send tokens” screen (after having said “send to someone” using TEST), the token I’m sending from isn’t selected by default

**Comment by tsejerome** [comment]
Cudn't replicate, can send some steps? thanks!

**Comment by aguycalled** [comment]
https://user-images.githubusercontent.com/24814046/167189199-3ccac129-abf8-4b62-b0a5-f5e1d7c35d9c.mp4

**Comment by aguycalled** [comment]
The bug is in `CardSelect`. `defaultOption` is received in the component but not stored in the state.

```typescript
const CardSelect = ({
  text,
  defaultOption,
  options,
  onSelect,
}: InputSelectProps) => {
  const theme = useTheme();
  const [selectedOption, setSelectedOption] = useState(defaultOption);
  const styles = useStyleSheet(themedStyles);
  const bottomSheet = useBottomSheet();

  console.log('selectedOption', selectedOption, 'defaultOption', defaultOption)
....
```

outputs:

```
 LOG  selectedOption  defaultOption TestToken account (100 TEST)
```

**Comment by aguycalled** [comment]
adding

```typescript
  useEffect(() => {
    setSelectedOption(defaultOption)
  }, [defaultOption]);
```

solves it

**Comment by aguycalled** [comment]
fixed in https://github.com/navcoin/WhisperWallet/commit/0d9fdf8a0a8aea45e639aaf9b510be17920afd54
