### ISSUE TITLE
Android Loading Splash Icon Blur

### ISSUE THREAD

**Issue by tsejerome** [navcoin/WhisperWallet#130]
![image](https://user-images.githubusercontent.com/20391660/166404212-1562f31c-9c91-45b9-9dc1-f9b85f5c1876.png)

**Comment by tsejerome** [comment]
![Screenshot_20220506-163829.png](https://user-images.githubusercontent.com/20391660/167097679-f110af03-c6ea-49c3-b8aa-73c6302e6509.png)

**Comment by tsejerome** [comment]
Now its not blur and not cropped as circle (actually kinda is coz the bottom left corner and bottom right corner is kinda cropped out but i think its no big deal)

tried to research for ways to make it larger, failed to achieve it but I think its good enough for now

**Comment by aguycalled** [comment]
cropped is fine. but it still looks pixelated

**Comment by tsejerome** [comment]
its bcoz we are putting a larger image into a smaller pixel, if you don't mind cropping half of the outer area of the image, we can stick with the original one but unblurred. (coz i recall you being shocked that its cropped)

**Comment by aguycalled** [comment]
what is the desired image size so it does not show pixelated?

**Comment by tsejerome** [comment]
I believe this is the closest we get ![Screenshot_20220506-175257.png](https://user-images.githubusercontent.com/20391660/167109642-f1518430-b3d9-4c95-a285-e4fd66288247.png)
