### ISSUE TITLE
iOS send email does not work if not using native mail client

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#137]
The send email button from the exception catcher does nothing if a different mail client than the native is used.

It should detect if it fails and fallback to the `Share` sheet.

**Comment by aguycalled** [comment]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/24814046/166970072-39eabd76-d227-4350-8d6b-a1504398e1a4.png">

**Comment by tsejerome** [comment]
I thot this was a conscious decision that we wanted to do mail instead of share previously

**Comment by aguycalled** [comment]
yes, but if email does not work we should detect it and alert the user or offer an alternative. email should be first

**Comment by aguycalled** [comment]
right now the wallet does not react if mail does not work

**Comment by tsejerome** [comment]
sure lets do that then :D
