### ISSUE TITLE
Back button throws you back to wallet completion screen

### ISSUE THREAD

**Issue by LordNelsson** [navcoin/WhisperWallet#141]
System: Android 10

Shortly after wallet creation, going to NavCash Pool Staking tab to view the address, copying it and then pressing 'back' throws me back to the 'wallet created' screen.

Added video for reference

https://user-images.githubusercontent.com/38504306/167260250-f716e0a2-cf23-4033-95ea-be06e93fd1d7.mp4

**Comment by LordNelsson** [comment]
Let me know if you're able to reproduce it on your end

**Comment by aguycalled** [comment]
can't replicate

![untitled](https://user-images.githubusercontent.com/24814046/167261580-b864d36b-7e7e-4d20-b752-b7c9a530dce8.gif)
