### ISSUE TITLE
Swapping Nav to xNav returns black screen (iOS Beta Mainnet)

### ISSUE THREAD

**Issue by HacheNAV** [navcoin/WhisperWallet#142]
Swapping Nav to xNav prompts a black screen and crashes the app.
Error from the log:

Here is my device info:
OS:unknown
Version:15.4.1
Brand:Apple
Model:iPhone 12 Pro

The error is as below: 
2022-05-07T15:09:12.890Z 
Fatal: ReferenceError Can't find variable: useEffect
***
App version is Beta release connected to the Mainnet.
Video attached.

https://user-images.githubusercontent.com/38258171/167260911-8884cc70-edcb-4c23-a485-852a5a57d79e.MOV

**Comment by aguycalled** [comment]
fixed in version 31
