### ISSUE TITLE
Swipe to confirm very low tolerance to vertical movement

### ISSUE THREAD

**Issue by LordNelsson** [navcoin/WhisperWallet#143]
When trying to confirm a transaction by swiping the bar, it is almost impossible through the vertical movement.

https://user-images.githubusercontent.com/38504306/167262675-079298c2-4417-4503-a9a6-8f874a2524e4.mp4

**Comment by aguycalled** [comment]
can you show a video?

**Comment by aguycalled** [comment]
android 10?

**Comment by LordNelsson** [comment]
> android 10?

Yep, on an Essential PH-1

**Comment by aguycalled** [comment]
should be fixed
