### ISSUE TITLE
iOS - wallet crashes when trying to access a previously created address

### ISSUE THREAD

**Issue by willoncio-nav** [navcoin/WhisperWallet#144]
Adding here that the wallet was created quite some versions back, which might be related

Here is my device info:
OS:unknown
Version:15.4.1
Brand:Apple
Model:iPhone XR

The error is as below: 
2022-05-08T06:09:29.524Z 
DatabaseClosed error: Error Wrong key

2022-05-08T06:09:23.054Z 
DatabaseClosed error: Error Wrong key

**Comment by aguycalled** [comment]
yes its because the wallet is pre-beta
