### ISSUE TITLE
IOS - scan a QR to send NAV to someone not working

### ISSUE THREAD

**Issue by ML-NAV** [navcoin/WhisperWallet#145]
Using the IOS app, when trying to send NAV to another address and I click on the QR icon, the camera is not opened, and no question is asked for permission to use the camera.
Checked under settings, there is no option to allow the whisper app to use the camera.

**Comment by aguycalled** [comment]
fixed in https://github.com/navcoin/WhisperWallet/commit/87ea86a695b65e505f74bf147975ad2412c1cc7c
