### ISSUE TITLE
IOS - Transactions are not sorted correctly

### ISSUE THREAD

**Issue by ML-NAV** [navcoin/WhisperWallet#146]
checking the transactions (under public amount, transaction history) does not show the transactions in the correct (by date) order.

**Comment by ML-NAV** [comment]
![whisper-transactions](https://user-images.githubusercontent.com/81147007/167293170-38b169ed-aa0b-4a9f-bc3b-4b96b145d9e5.png)

**Comment by aguycalled** [comment]
I can't replicate this on my wallet. would you mind sharing your mnemonic with me over discord?

**Comment by ML-NAV** [comment]
I see, they are not correct on my end.
Did remove/add the wallet and now appear fine.

Will make some more tests. If i'm the only one it's no issue i would think.

**Comment by tsejerome** [comment]
Conscious decision: Adding block height on each Card so that users can know that it is sorted according to block height instead of the date descending

Another decision is to add the state of each card, e.g. pending/immature.

@aguycalled can you suggest the relevant states

**Comment by aguycalled** [comment]
closing as can't replicate
