### ISSUE TITLE
AccountsTab: Tapping on the background of a bottom sheet does not close it

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#149]
Dragging down the sheet closes it, but freezes the app after.

Does not happen outside of AccountsTab.

Issue seen on iOS.

**Comment by tsejerome** [comment]
Also happening on android

**Comment by tsejerome** [comment]
from the inspector, it seems that the backdrop of the bottom sheet still exists

**Comment by tsejerome** [comment]
blocked by reviewing of https://github.com/navcoin/WhisperWallet/pull/153 and development of https://github.com/navcoin/WhisperWallet/pull/150

**Comment by aguycalled** [comment]
fixed
