### ISSUE TITLE
Add explanatory text detailing how to add the recovery words during a wallet import

### ISSUE THREAD

**Issue by HacheNAV** [navcoin/WhisperWallet#158]
Maybe we can explain bit better how to type the recovery words during a wallet import, something like:
"Type all the recovery words in the original order followed by a gap."
![IMG_5664](https://user-images.githubusercontent.com/38258171/168486156-1ca3f6a0-4e55-45c5-b573-db6e5d7a40e5.PNG)

**Comment by aguycalled** [comment]
fixed in 301889e
