### ISSUE TITLE
Cold Staked coins don't show up in Whisper after wallet import (Beta Mainnet)

### ISSUE THREAD

**Issue by HacheNAV** [navcoin/WhisperWallet#159]
Coins were being cold staked in Whisper -> Core full node in iOS.
After a:
- WhisperWallet update (34 -> 35)
- re-importing back the previous wallet using the mnemonic (it was needed)
- adding back the staking node to the WhisperWallet
The coins that were being cold staked previously are not showing up in Whisper (but they still do show up in the Core node Wallet in iOS).
***
Whisper beta version 35
Mainnet
iOS 15.4.1
iPhone 12 Pro

**Comment by aguycalled** [comment]
does refreshing help?

**Comment by HacheNAV** [comment]
No, it doesn't help. Neither does closing and reopening the app, which syncs again the txs.

**Comment by aguycalled** [comment]
ok will have a look, this new version has a new database backend which might need some fine-tuning

**Comment by HacheNAV** [comment]
This issue is fixed now with the latest versions of the wallet.
