### ISSUE TITLE
IOS - Screen blank/white when checking transaction details

### ISSUE THREAD

**Issue by ML-NAV** [navcoin/WhisperWallet#162]
When checking details of a transaction (doesn't matter if it's normal, private or staking) the screen becomes white.

https://user-images.githubusercontent.com/81147007/170817471-cda02054-5bc3-4fb0-92c5-8d990f9ac80c.MP4

Just updated to IOS 15.5, i'm not sure if the issue was before the update.

**Comment by aguycalled** [comment]
fixed in ecba6cf
submitting to TestFlight now
