### ISSUE TITLE
Font colour and seed confirm boxes

### ISSUE THREAD

**Issue by GreggyGB** [navcoin/WhisperWallet#165]
Samsung S8
![Screenshot_20220601-175502_Whisper](https://user-images.githubusercontent.com/43723411/171462238-934b5c84-a89e-4040-8939-560c4b48f738.jpg)
Wallet name is actually typed in

![Screenshot_20220601-180037_Whisper](https://user-images.githubusercontent.com/43723411/171462301-371d4626-81e4-4be3-8542-1c50aea85286.jpg)
Seed confirm screen

G

**Comment by aguycalled** [comment]
can you please try to re download the apk?

**Comment by GreggyGB** [comment]
Sure. Still the same

**Comment by aguycalled** [comment]
sorry, uploaded the file in the wrong location. should be fine now

**Comment by GreggyGB** [comment]
Sorted
