### ISSUE TITLE
Scrolling not going far enough

### ISSUE THREAD

**Issue by GreggyGB** [navcoin/WhisperWallet#171]
Samsung S8

When typing in send transaction it doesn't scroll far enough to show amount for transfer.
For seed words buttons are overlaping last line if words
![Screenshot_20220604-152414_Whisper](https://user-images.githubusercontent.com/43723411/172006995-b06510d0-641f-411c-ac7d-20a5d129ce89.jpg)

**Comment by aguycalled** [comment]
fixed in [07808a1](https://github.com/navcoin/WhisperWallet/commit/07808a1564e07d552542e49196398d105d1a3828)

will update apk tomorrow
