### ISSUE TITLE
Amount field does not remove the initial 0

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#94]
On a new `SendTo` screen, when the user taps and inputs an amount, the initial 0 is not removed:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/24814046/164401229-f0e35fb2-119a-4a78-b92e-c18747855cfd.png">

The amount should be parsed, and in this example, show 1 instead of 01

**Comment by tsejerome** [comment]
It's intentionally designed to be like that in case user wanna type 0.xxx in the amount

Workaround:
1) don't have default value (user doesn't know it can be filled)
2) on focus highlight the whole value so the whole string will be replaced

**Comment by aguycalled** [comment]
Why don't we use the 0 as a placeholder?

**Comment by tsejerome** [comment]
lmao i forgot the existence of that
