### ISSUE TITLE
Android AccountsTab ScrollView does not scroll

### ISSUE THREAD

**Issue by aguycalled** [navcoin/WhisperWallet#95]
![untitled](https://user-images.githubusercontent.com/24814046/164530696-c089a84a-6560-47e8-9526-3fac880384c2.gif)

**Comment by tsejerome** [comment]
I think it's not supposed to be scrolling as the screens has shown all of them alrdy and this is how native android looks
but I will double check tmr

**Comment by aguycalled** [comment]
iOS looks in a more natural way. the spinner showing on top of the items looks weird imo

**Comment by tsejerome** [comment]
I find it weird to have a pull to refresh at the lower half of the page, how about we just have a full page refresh button at the top right corner next to the "..." menu?

**Comment by aguycalled** [comment]
it does not make sense to me. the bottom part is what gets scrolled. users can have an arbitrary amount of private tokens and will need to scroll through them

**Comment by tsejerome** [comment]
@aguycalled is there any app that has half page scrollview that you cud send over for us to reference?

**Comment by aguycalled** [comment]
I can't think now of any app that has half page scroll view, but I think it is what makes more sense in our ui. it looks good to me on ios

**Comment by tsejerome** [comment]
Alrighty, but I believe the scroll is perfectly normal for android users ( i have been seeing it like this for years )

**Comment by tsejerome** [comment]
Conclusion: adding a reload button at the top
